name: ci
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.6.0
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dotnet
        uses: actions/setup-dotnet@v3.2.0
        with:
          # renovate: datasource=dotnet depName=dotnet-sdk
          dotnet-version: 7.0.402

      - name: Cache packages
        uses: actions/cache@v3.3.2
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: ${{ runner.os }}-nuget-${{ hashFiles('.config/dotnet-tools.json', '**/packages.lock.json') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Cake build
        run: ./test-build.ps1
